spring:
  application:
    name: shg-trip-back
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    repair-on-migrate: true

cloud:
  aws:
    s3:
      region: ${AWS_REGION:ap-northeast-2}
      bucket: ${S3_BUCKET:shgtrip-data}