-- S3 연동을 위한 places 테이블 컬럼 추가
ALTER TABLE places ADD COLUMN IF NOT EXISTS source VARCHAR(50);
ALTER TABLE places ADD COLUMN IF NOT EXISTS tags TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;
